# Generated by Django 2.2.6 on 2019-10-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DocumentType'),
        ),
    ]
