# Generated by Django 2.2.6 on 2019-10-25 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191025_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeexpense',
            options={'ordering': ('user', '-expense_date')},
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='hourly_rate',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='employeetimesheet',
            name='hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
